###############################################################################
#                          Settings for g method                              #
###############################################################################

##### Method settings #####
# The method name
model: 'g'
# Size of the input
input_size: null
# List estimated signals
signals: ['pulse']

##### rPPG settings #####
# The ROI used as model input
roi_method: 'face'
# The target sampling frequency [Hz]
fps_target: 30
# Overlap of windows during estimation
est_window_overlap: 0
# Size of window during estimation
est_window_length: 64
